### ISSUE TITLE
Handling of internal and external dependencies of packages

### ISSUE THREAD

**Issue by benjaminbollen** [OpenST/developer-guidelines#1]
[**Updated** 20190403]

We are of the opinion that we should use `^` where possible and sensible to ensure we run with the most recent updated dependencies. The lock file should be committed and updated at regular intervals.

We decided to use the `^` symbol or version ranges for "internal" dependencies. Internal dependencies are projects under the `@openst` project.

[ **Updated** 20190411]
For external dependencies we want to use fixed versions.

Until we are at version `1.0.0`, we should use a version range like `>=0.10.0 <0.11.0` to prevent propagation of breaking changes in newer minor versions.

The scope of this ticket is exclusively an update to the developer guidelines.

**Comment by schemar** [comment]
First thing that comes to mind is https://github.com/dominictarr/event-stream/issues/116

**Comment by schemar** [comment]
Two more points

* Web3 `1.0.0-beta.38` has breaking changes from `beta.37`
* We may also differentiate between internal and external dependencies.
  * Ref. https://github.com/OpenSTFoundation/brandedtoken.js/pull/115
