### ISSUE TITLE
write release notes on Github for 0.10

### ISSUE THREAD

**Issue by benjaminbollen** [OpenST/developer-guidelines#13]
- [x] openst-contracts https://github.com/OpenST/openst-contracts/releases/tag/0.10.0-rc.3
- [x] openst.js https://github.com/OpenST/openst.js/releases/tag/0.10.0-beta.2
- [x] brandedtoken-contracts https://github.com/OpenST/brandedtoken-contracts/releases/tag/0.10.0-rc.1
- [x] brandedtoken.js https://github.com/OpenST/brandedtoken.js/releases/tag/0.10.0-beta.1
- [x] mosaic-contracts https://github.com/OpenST/mosaic-contracts/releases/tag/0.10.0-rc.1
- [x] mosaic.js https://github.com/OpenST/mosaic.js/releases/tag/0.10.0-beta.5
- [ ] mosaic-chains

**Comment by benjaminbollen** [comment]
next up:
- publish new tags on the master commits
- move the release notes

**Comment by achirala** [comment]
Release notes for edits/suggestions: 
https://docs.google.com/document/d/16XkQ-lBHcX7E_qeix5en0--aB7464qc6pzYydyGUj7c/edit
