### ISSUE TITLE
push tag on master and publish NPM 0.10.0 

### ISSUE THREAD

**Issue by benjaminbollen** [OpenST/developer-guidelines#15]
* [x] update the release branch with the correct version number
    * [x] mosaic-contracts
        * [x] PRs
    * [x] mosaic.js
        * [x] PRs
    * [x] openst-contracts
        * [x] PRs
    * [x] openst.js
        * [x] PRs
    * [x] brandedtoken-contracts
        * [x] PRs
    * [x] brandedtoken.js
        * [x] PRs
* [x] merge release into master and develop
    * [x] mosaic-contracts
        * [x] PRs
    * [x] mosaic.js
        * [x] PRs
    * [x] openst-contracts
        * [x] PRs
    * [x] openst.js
        * [x] PRs
    * [x] brandedtoken-contracts
        * [x] PRs
    * [x] brandedtoken.js
        * [x] PRs
* [x] create a tag on master
    * [x] mosaic-contracts
    * [x] mosaic.js
    * [x] openst-contracts
    * [x] openst.js
    * [x] brandedtoken-contracts
    * [x] brandedtoken.js
* [x] publish the release on `npm`
    * [x] mosaic-contracts
    * [x] mosaic.js
    * [x] openst-contracts
    * [x] openst.js
    * [x] brandedtoken-contracts
    * [x] brandedtoken.js
* [x] write release on GitHub
    * [x] mosaic-contracts
    * [x] mosaic.js
    * [x] openst-contracts
    * [x] openst.js
    * [x] brandedtoken-contracts
    * [x] brandedtoken.js

**Comment by schemar** [comment]
@benjaminbollen should I delete the release branches in the process (as per [GitFlow](https://nvie.com/posts/a-successful-git-branching-model/#release-branches))?

**Comment by benjaminbollen** [comment]
no, please.  i understand it's not needed anymore, but for my own comfort, id prefer to keep them around for a while until after release.

**Comment by schemar** [comment]
I will:

* update the release branch with the correct version number
* merge release into master
* create a tag on master
* publish the release on `npm`

@benjaminbollen are there release notes for all the releases?

**Comment by benjaminbollen** [comment]
the release notes for the repo have been published on the github page

**Comment by benjaminbollen** [comment]
release has been merged into develop and master

**Comment by schemar** [comment]
@benjaminbollen what about mosaic-chains (see also #13)?

**Comment by schemar** [comment]
Make JS updates **after** contracts in order to update the dependencies as well.
