### ISSUE TITLE
Labels should be unified across repositories

### ISSUE THREAD

**Issue by schemar** [OpenST/developer-guidelines#7]
We need to:

* decide which labels are required,
* decide how to set-up the labels (colors and names),
* create the labels across all L3 repositories,
* and start applying the labels to new tickets.

**Comment by pgev** [comment]
Here is my preferred list:

```
breaking-change
good-first-issue
showstopper

kind​:bug
kind:documentation
kind:feature
kind:enhancement
kind:question
kind:research

release:v0.9.4
release:v0.10.0

resolution:done
resolution:duplicate
resolution:invalid
resolution:wontfix
```

*area* can be useful if we would like to run some statistics, however, we should maybe skip it at the beginning:

```
area:contracts
area:infrastructure
area:tests
```

Setting *priority* is not obvious always. For simplification, we can now go with *showstopper* only label (in top list) and not have priority at all.
```
priority:critical
priority:high
priority:low
priority:medium
```

**Comment by schemar** [comment]
Labels which I think are necessary:

1. why was the ticket opened?
    * bug
    * enhancement
    * documentation
    * research
2. why was the ticket closed?
    * fixed
    * duplicate
    * wontfix
    * invalid

I may well have forgotten some labels in both sections.

Additionally, there could be priority labels. I would vote for only two labels here:

* high priority
* show stopper

A label like "normal" seems redundant to me. A label like "low" priority I think is difficult. Maybe close the ticket instead? Who has time for low priority tickets?

I also like "good first issue" and "help needed".

**Comment by schemar** [comment]
@pgev adding release labels would mean tracking the release information redundantly. Once in ZenHub plus as a label (adding *and* removing).

**Comment by jasonklein** [comment]
I largely agree with @schemar and @pgev.

I especially second's Pro's view that the "area" would be a helpful indication.

Where I part from Pro is that "area:contracts" seems too opaque to me, because within the contracts there may be multiple large but well-defined topics, like token, rules, proxies, gnosis safe modules, and external for OpenST, some of which are significant work streams in their own right. So, assuming Pro's system, I would vote for "area:<contract area>" which is at the same "level" as the other areas.

**Comment by pgev** [comment]
@schemar I do agree, however, was thinking that once we move out from Zenhub, this information would be lost. Thoughts?

**Comment by pgev** [comment]
> @pgev adding release labels would mean tracking the release information redundantly. Once in ZenHub plus as a label (adding _and_ removing).

@schemar I do agree, however, was thinking that once we move out from Zenhub, this information would be lost. Thoughts?

**Comment by pgev** [comment]
> I largely agree with @schemar and @pgev.
> 
> I especially second's Pro's view that the "area" would be a helpful indication.
> 
> Where I part from Pro is that "area:contracts" seems too opaque to me, because within the contracts there may be multiple large but well-defined topics, like token, rules, proxies, gnosis safe modules, and external for OpenST, some of which are significant work streams in their own right. So, assuming Pro's system, I would vote for "area:" which is at the same "level" as the other areas.

@jasonklein Banks what about having a `component:*` as an addition to `area:*` ?

**Comment by jasonklein** [comment]
> > @pgev adding release labels would mean tracking the release information redundantly. Once in ZenHub plus as a label (adding _and_ removing).
> 
> @schemar I do agree, however, was thinking that once we move out from Zenhub, this information would be lost. Thoughts?

Related to @pgev's point, @schemar we should keep in mind that not everyone uses ZenHub (i.e., those who are not on the internal team), so we might have to accept some redundant communications/administration.

**Comment by jasonklein** [comment]
> @jasonklein Banks what about having a `component:*` as an addition to `area:*` ?

@pro: that would work for me (but I'm not terribly concerned with the specific label).

**Comment by benjaminbollen** [comment]
thanks for the great input; I propose following labels

```
opened:bug
opened:feature
opened:enhancement
opened:research
opened:documentation

closed:duplicate
closed:wontfix
closed:invalid

priority:critical
priority:high

info:breaking-change
info:good-first-issue
info:help-wanted
```

some remarks to illustrate my thinking; 1. "done" is implicit when closing without specific closed label. 2. the first aim is to find a minimal set of helpful labels, that in practice are used across all repositories. So I propose we leave out `area:` or other too granular labels at this point in time.

Personal suggestion, we use only four colours for `opened:`, `closed:`, `priority:` and `info:`

**Comment by pgev** [comment]
Thanks @benjaminbollen for propose. Looks good to me. Please, see my comments below, however, those are suggestions.

> thanks for the great input; I propose following labels
> 
> ```
> opened:bug
> opened:feature
> opened:enhancement
> opened:research
> opened:documentation

I would propose to have *kind* or *type* for issue types.

> 
> closed:duplicate
> closed:wontfix
> closed:invalid

(In JIRA closed is a resolution type.)

> 
> priority:critical
> priority:high
> 
> info:breaking-change
> info:good-first-issue
> info:help-wanted
> ```
> 
> some remarks to illustrate my thinking; 1. "done" is implicit when closing without specific closed label. 2. the first aim is to find a minimal set of helpful labels, that in practice are used across all repositories. So I propose we leave out `area:` or other too granular labels at this point in time.
> 
> Personal suggestion, we use only four colours for `opened:`, `closed:`, `priority:` and `info:`

**Comment by pgev** [comment]
Closed by mistake.

**Comment by benjaminbollen** [comment]
task is twofold: apply in developer guidelines and update the labels in the repos consistently

**Comment by benjaminbollen** [comment]
choose soft / beautiful colors in the range

green - opened
orange - closed
red - priority
blue - info
